import { NextResponse } from 'next/server';
import dbConnect from '@/lib/mongodb';
import Booking from '@/models/Booking';
import Vehicle from '@/models/Vehicle';
import User from '@/models/User';
import jwt from 'jsonwebtoken';
import { cookies } from 'next/headers';
import { sendBookingConfirmationEmail } from '@/lib/emailService';

export async function POST(request: Request) {
// ... existing POST logic ...
  try {
    await dbConnect();
    const body = await request.json();
    
    // Validate required fields
    const { customerEmail, vehicleId, startDate, endDate, pickupLocation, dropoffLocation } = body;
    
    if (!customerEmail || !vehicleId || !startDate || !endDate || !pickupLocation || !dropoffLocation) {
        return NextResponse.json({ error: 'Missing required booking information' }, { status: 400 });
    }
    
    // Check if vehicle exists and is available
    const vehicle = await Vehicle.findById(vehicleId);
    if (!vehicle) {
        return NextResponse.json({ error: 'Vehicle not found' }, { status: 404 });
    }
    if (!vehicle.available) {
        return NextResponse.json({ error: 'Vehicle is currently unavailable' }, { status: 400 });
    }
    
    // Calculate total price (simplified logic)
    const start = new Date(startDate);
    const end = new Date(endDate);
    const diffTime = Math.abs(end.getTime() - start.getTime());
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24)) || 1; // Minimum 1 day
    const totalPrice = diffDays * vehicle.pricing.daily;
    
    // Find or create customer (simplified for now to just fail if user not found, strict enterprise mode)
    const user = await User.findOne({ email: customerEmail });
    if (!user) {
         return NextResponse.json({ error: 'User not registered. Please sign up first.' }, { status: 400 });
    }

    const booking = await Booking.create({
        customer: user._id,
        vehicle: vehicleId,
        company: vehicle.company,
        startDate,
        endDate,
        pickupLocation,
        dropoffLocation,
        totalPrice,
        status: 'pending'
    });

    // Send Confirmation Email (Fire and forget)
    sendBookingConfirmationEmail(user.email, {
        bookingNumber: booking.bookingNumber, // Assuming bookingNumber is auto-generated by Mongoose plugin or defaults
        vehicleName: `${vehicle.brand} ${vehicle.vehicleModel}`,
        startDate,
        endDate,
        pickupLocation,
        dropoffLocation,
        totalPrice,
        status: booking.status
    }).catch(console.error);
    
    return NextResponse.json({ success: true, data: booking }, { status: 201 });
  } catch (error) {
    console.error(error);
    return NextResponse.json({ success: false, error: 'Failed to create booking' }, { status: 500 });
  }
}

// ... POST method above ...

export async function GET(request: Request) {
    try {
        await dbConnect();
        
        const cookieStore = await cookies();
        const token = cookieStore.get('token')?.value;

        if (!token) {
            return NextResponse.json({ success: false, error: 'Not authorized' }, { status: 401 });
        }

        const decoded = jwt.verify(token, process.env.JWT_SECRET!) as { id: string, role: string };
        const user = await User.findById(decoded.id);

        if (!user) {
            return NextResponse.json({ success: false, error: 'User not found' }, { status: 404 });
        }

        let query = {};
        if (user.role === 'customer') {
            query = { customer: user._id };
        } else if (user.role === 'company_owner') {
             // If company owner has a companyId, filter by company
             if (user.companyId) {
                query = { company: user.companyId };
             } else {
                 // Fallback if no company assigned yet
                 query = { dummy: 'no_results' }; 
             }
        }
        
        const bookings = await Booking.find(query)
            .populate('vehicle')
            .populate('customer', 'firstName lastName email')
            .sort({ createdAt: -1 });
        
        return NextResponse.json({ success: true, data: bookings });
    } catch (error) {
        console.error('Booking fetch error:', error);
        return NextResponse.json({ success: false, error: 'Failed to fetch bookings' }, { status: 500 });
    }
}
